// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgcztxIPzU-tGXR_R9PxIavhlN02eb7XM',
    appId: '1:893078377498:web:5a06f18d9455f774d1eda3',
    messagingSenderId: '893078377498',
    projectId: 'islami-app-8276e',
    authDomain: 'islami-app-8276e.firebaseapp.com',
    storageBucket: 'islami-app-8276e.firebasestorage.app',
    measurementId: 'G-92HFHHZGSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIDYDExkwVR9Ye5Olg7-Sm79yf7xpVjrk',
    appId: '1:893078377498:android:88478e80aaa75d3ad1eda3',
    messagingSenderId: '893078377498',
    projectId: 'islami-app-8276e',
    storageBucket: 'islami-app-8276e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSx2a8ZqReXSX-yaUzl1sBlQlaNhbMTTU',
    appId: '1:893078377498:ios:58dbbea1c46f29f5d1eda3',
    messagingSenderId: '893078377498',
    projectId: 'islami-app-8276e',
    storageBucket: 'islami-app-8276e.firebasestorage.app',
    iosBundleId: 'com.example.islamiApp',
  );
}
